workbridgetest1/inicio/urls.py
# urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('login/', views.login_view, name='login'),
    path('Usuarios/logout', views.loginsalir),
    path('indexA/', views.admin_dashboard, name='admin_dashboard'),    
    path('empresa_dashboard/', views.empresa_dashboard, name='empresa_dashboard'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('users/', views.user_list, name='user_list'),
    path('users/create/', views.user_create, name='user_create'),
    path('users/<int:pk>/edit/', views.user_update, name='user_update'),
    path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('perfil/', views.perfil, name='perfil'),

]

workbridgetest1/task1/urls.py
from django.contrib import admin
from django.urls import path, include
from django import views
from . import views
from task1 import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('inicio/', views.inicio, name='inicio'),
    path('creacion/', views.proyectoinsertar, name='creacion'),
    path('indexA/', views.indexA, name='indexA'),
    path('indexE/', views.indexE, name='indexE'),
    path('indexU/', views.indexU, name='indexU'),
    path('inicioE/', views.inicioE, name='inicioE'),
    path('proyectos/actualizar/<int:id>/', views.actualizarproyecto, name='actualizar'),
    path('proyectos/eliminar/<int:id>/', views.borrarproyecto, name='borrar'),
    path('comentariosA/<int:proyecto_id>/', views.comentarios_proyectoA, name='comentariosA'),
    path('comentariosE/<int:proyecto_id>/', views.comentarios_proyectoE, name='comentariosE'),  
    path('comentariosU/<int:proyecto_id>/', views.comentarios_proyectoU, name='comentariosU'),
    path('estadisticas/proyectos/', views.estadisticas_proyectos, name='estadisticas_proyectos'),
    path('estadisticas/', views.estadisticas, name='estadisticas'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workbridgetest1/workbridgetest1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('task1.urls')),
     path('', include('inicio.urls')),
]

workbridgetest1/inicio/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
import uuid

class User(AbstractUser):
    is_admin = models.BooleanField('Is admin', default=False)
    is_empresa = models.BooleanField('Is empresa', default=False)
    nombres = models.CharField('Nombres', max_length=50,default='')
    apellidos = models.CharField('Apellidos', max_length=50, default='')
    correo = models.EmailField('Correo', unique=True, default='')
    telefono = models.CharField('Teléfono', max_length=15,default='')
    genero = models.CharField('Género', max_length=10, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='')
    direccion = models.CharField('Dirección', max_length=255,default='')
    
    username = models.CharField(max_length=150, unique=True, default=uuid.uuid4)

    USERNAME_FIELD = 'correo'
    REQUIRED_FIELDS = ['username', 'nombres', 'apellidos']

    def __str__(self):
        return self.correo



class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
   
    fecha_de_nacimiento = models.DateField('Fecha de nacimiento', blank=True, null=True)
    direccion_sede = models.CharField('Dirección de la Sede', max_length=255, blank=True, null=True)
    telefono_empresa = models.CharField('Teléfono de la Empresa', max_length=15, blank=True, null=True)
    telefono_empresa2 = models.CharField('Teléfono de la Empresa', max_length=15, blank=True, null=True)
    numero_identificacion_fiscal = models.CharField('Número de Identificación Fiscal', max_length=50, blank=True, null=True)
    tipo_empresa = models.CharField('Tipo de Empresa', max_length=100, blank=True, null=True)
    sector_empresa = models.CharField('Sector de la Empresa', max_length=100, blank=True, null=True)
    numero_empleados = models.IntegerField('Número de Empleados', blank=True, null=True)
    descripcion_empresa = models.TextField('Descripción de la Empresa', blank=True, null=True)

    def __str__(self):
        return self.user.correo

workbridgetest1/inicio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import authenticate
from .models import User,Profile
from django.core.exceptions import ValidationError
import re
from datetime import date
from django.utils.translation import gettext_lazy as _

class RegistroForm(UserCreationForm):
    rol = forms.ChoiceField(choices=[('empresa', 'Empresa')], label=_('Rol'))
    genero = forms.ChoiceField(
        choices=[('', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino')],
        label=_('Género'),
        required=False,  
        initial=''  
    )

    class Meta:
        model = User
        fields = ['rol', 'nombres', 'apellidos', 'correo', 'telefono', 'genero', 'direccion', 'password1', 'password2']
        labels = {
            'nombres': _('Nombres'),
            'apellidos': _('Cargo'),  
            'correo': _('Correo electrónico'),
            'telefono': _('Teléfono'),
            'direccion': _('Dirección'),
        }
        error_messages = {
            'correo': {
                'unique': _("Ya existe un usuario con este correo."),
            },
            'password1': {
                'password_too_short': _("Esta contraseña es demasiado corta. Debe contener al menos 8 caracteres."),
            },
        }

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            self.add_error('password2', _("Las contraseñas no coinciden"))
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

class LoginForm(AuthenticationForm):
    correo = forms.EmailField(label=_("Correo electrónico"), widget=forms.EmailInput(attrs={'autofocus': True}))

    class Meta:
        fields = ['correo', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = self.fields['correo'].widget
        del self.fields['correo']

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password) 
            if self.user_cache is None:
                raise forms.ValidationError(
                    _("Usuario o contraseña inválidos."),
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data
    


class ProfileForm(forms.ModelForm):
    fecha_de_nacimiento = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False
    )

    class Meta:
        model = Profile
        fields = [
            'fecha_de_nacimiento',
            'direccion_sede',
            'telefono_empresa',
            'telefono_empresa2',
            'numero_identificacion_fiscal',
            'tipo_empresa',
            'sector_empresa',
            'numero_empleados',
            'descripcion_empresa'
        ]

    def clean_fecha_de_nacimiento(self):
        fecha_de_nacimiento = self.cleaned_data.get('fecha_de_nacimiento')
        if fecha_de_nacimiento and fecha_de_nacimiento > date.today():
            raise ValidationError('La fecha de nacimiento no puede ser en el futuro.')
        return fecha_de_nacimiento

    def clean_telefono_empresa(self):
        telefono_empresa = self.cleaned_data.get('telefono_empresa')
        if telefono_empresa and not re.match(r'^\+?1?\d{5,15}$', telefono_empresa):
            raise ValidationError('El número de teléfono debe ser válido. Debe contener entre 9 y 15 dígitos.')
        return telefono_empresa

    def clean_telefono_empresa2(self):
        telefono_empresa2 = self.cleaned_data.get('telefono_empresa2')
        if telefono_empresa2 and not re.match(r'^\+?1?\d{5,15}$', telefono_empresa2):
            raise ValidationError('El número de teléfono debe ser válido. Debe contener entre 9 y 15 dígitos.')
        return telefono_empresa2

    def clean_numero_identificacion_fiscal(self):
        numero_identificacion_fiscal = self.cleaned_data.get('numero_identificacion_fiscal')
        if numero_identificacion_fiscal and not re.match(r'^[A-Z0-9]+$', numero_identificacion_fiscal):
            raise ValidationError('El número de identificación fiscal solo puede contener letras mayúsculas y números.')
        return numero_identificacion_fiscal

    def clean_numero_empleados(self):
        numero_empleados = self.cleaned_data.get('numero_empleados')
        if numero_empleados and (numero_empleados < 0 or numero_empleados > 100000):
            raise ValidationError('El número de empleados debe estar entre 0 y 100000.')
        return numero_empleados

    def clean(self):
        cleaned_data = super().clean()
        direccion_sede = cleaned_data.get('direccion_sede')
        telefono_empresa = cleaned_data.get('telefono_empresa')
        numero_identificacion_fiscal = cleaned_data.get('numero_identificacion_fiscal')

        # Validación condicional: Si uno de los campos de empresa está presente, todos deben estar presentes.
        if any([direccion_sede, telefono_empresa, numero_identificacion_fiscal]):
            if not all([direccion_sede, telefono_empresa, numero_identificacion_fiscal]):
                raise ValidationError('Todos los campos relacionados con la empresa deben ser completados.')

        return cleaned_data

workbridgetest1/inicio/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .decorators import admin_required, empresa_required
from .forms import RegistroForm, LoginForm,ProfileForm
from django.views.decorators.cache import never_cache
from .models import User,Profile
import uuid


#Login-Registro
@never_cache
@login_required
def logout_view(request):
    logout(request)
    response = redirect('login') 
    response['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response['Pragma'] = 'no-cache'
    response['Expires'] = '0'
    return response

def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            rol = form.cleaned_data['rol']

            if rol == 'empresa':
                user.is_empresa = True
            elif rol == 'admin':
                user.is_admin = True

            user.username = str(uuid.uuid4())
            user.save()
            messages.success(request, "Registrado.")
            return redirect('login')
        else:
            messages.error(request, "Problemas en el registro.")
    else:
        form = RegistroForm()

    return render(request, 'accounts/registro.html', {'form': form})

def login_view(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
               
                if user.is_admin:
                    request.session['rol_usuario'] = 'Admin'
                    return redirect('admin_dashboard')
                elif user.is_empresa:
                    request.session['rol_usuario'] = 'Empresa'
                    return redirect('empresa_dashboard')
                else:
                    request.session['rol_usuario'] = 'Usuario' 
            else:
                messages.error(request, "Usuario o contraseña invalido.")
        else:
            messages.error(request, "Se proporcionaron datos de inicio de sesión no válidos.")

    return render(request, 'accounts/login.html', {'form': form})

@never_cache
@admin_required
def admin_dashboard(request):
    return render(request, 'task1/templates/interfaz_admin/home/indexA.html')


@never_cache
@empresa_required
def empresa_dashboard(request):
    user = request.user
    try:
        profile = user.profile
    except Profile.DoesNotExist:
        profile = None
    return render(request, 'accounts/empresa_dashboard.html', {'user': user, 'profile': profile})

@login_required
def editar_perfil(request):
    user = request.user
    try:
        profile = Profile.objects.get(user=user)
    except Profile.DoesNotExist:
      
        profile = Profile(user=user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('empresa_dashboard')  
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'accounts/editar_perfil.html', {'form': form})

@admin_required
@login_required
def perfil(request):
    user = request.user
    return render(request, 'accounts/perfil.html', {'user': user})



#Crud usuarios/registro

@login_required
@admin_required
def user_list(request):
    users = User.objects.all() 
    return render(request, 'users/user_list.html', {'users': users})

@login_required
@admin_required
def user_create(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            rol = form.cleaned_data['rol']

            if rol == 'admin':
                user.is_admin = True
            elif rol == 'empresa':
                user.is_empresa = True

            user.username = str(uuid.uuid4())
            user.save()
            messages.success(request, 'Usuario creado con éxito.')
            return redirect('user_list')
        else:
            messages.error(request, 'Error en la creación del usuario.')
    else:
        form = RegistroForm()
    return render(request, 'users/user_form.html', {'form': form})

@login_required
@admin_required
def user_update(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = RegistroForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            messages.success(request, 'Usuario actualizado con éxito.')
            return redirect('user_list')
        else:
            messages.error(request, 'Error en la actualización del usuario.')
    else:
        form = RegistroForm(instance=user)
    return render(request, 'users/user_form.html', {'form': form})

@login_required
@admin_required
def user_delete(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.delete()
        messages.success(request, 'Usuario eliminado con éxito.')
        return redirect('user_list')
    return render(request, 'users/user_confirm_delete.html', {'user': user})


def loginsalir(request):
    logout(request)
    return redirect('/login')

workbridgetest1/inicio/templates/accounts/editar_perfil.html
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow-sm" style="max-width: 600px; margin: auto;">
        <h2 class="card-header bg-primary text-white text-center">Editar Perfil</h2>
        <div class="card-body">
            <form method="post" id="edit-profile-form">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% if field.field.widget.input_type == 'date' %}
                        <input type="text" name="{{ field.name }}" id="{{ field.id_for_label }}" value="{{ field.value|default_if_none:'' }}" class="form-control datepicker">
                    {% else %}
                        {{ field }}
                    {% endif %}
                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                {% endfor %}
                
                {% if form.non_field_errors %}
                <div class="alert alert-danger mt-3">
                    <ul class="mb-0">
                        {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                
                <button type="submit" class="btn btn-primary btn-block">Guardar Cambios</button>
            </form>
        </div>
    </div>
</div>

<style>
    /* Estilos personalizados para la página */
    body {
        font-family: 'Nunito', sans-serif;
        background: url("{% static 'inicio/img/pexels-pixabay-434659.jpg' %}") no-repeat center center fixed;
        background-size: cover;
        margin: 0;
        color: #333;
    }

    .container {
        background-color: rgba(233, 242, 249, 0.8); /* Fondo ligeramente transparente */
        padding: 20px;
        border-radius: 10px;
    }

    .card {
        border: none;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card-header {
        border-bottom: none;
        border-radius: 8px 8px 0 0;
        padding: 20px;
    }

    .card-body {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 0 0 8px 8px;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-group label {
        font-weight: bold;
    }

    .form-group input,
    .form-group textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 5px;
    }

    .form-group input.error,
    .form-group textarea.error {
        border-color: #dc3545;
    }

    .form-text {
        margin-top: 5px;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        transition: background-color 0.3s, border-color 0.3s;
        padding: 12px;
        font-size: 16px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #004b9f;
    }

    .alert {
        background-color: #f8d7da;
        border-color: #f5c6cb;
        color: #721c24;
        padding: 10px;
        border-radius: 5px;
    }

    @media (max-width: 768px) {
        .container {
            padding: 15px;
        }
    }

    @media (max-width: 576px) {
        .btn-primary {
            font-size: 14px;
            padding: 10px;
        }
    }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"/>

<script>
    $(document).ready(function(){
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            todayHighlight: true
        });
    });
</script>

{% endblock %}

workbridgetest1/inicio/templates/accounts/empresa_dashboard.html
{% load static %}

{% include 'interfaz_empresa/pie/headerE.html' %}

{% block content %}
<div class="ui container" style="margin-top: 40px;">
    {% if profile %}
    <div class="ui centered card" style="width: 100%; padding: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
        <img src="{% static 'inicio/img/usericon.png' %}" alt="Imagen de perfil del administrador" style="border-radius: 50%; width: 150px; height: 150px; display: block; margin: auto; margin-bottom: 20px;">
        <div class="content">
            <h2 class="ui header" style="text-align: center; font-size: 2rem;">Perfil de Empresa</h2>
            <div class="ui divider"></div>
            <div class="ui stackable grid">
                <div class="eight wide column">
                    <div class="ui list">
                        <div class="item">
                            <i class="edit icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Nombre:</strong> {{ user.nombres }} 
                            </div>
                        </div>
                        <div class="item">
                            <i class="user icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Cargo:</strong> {{ user.apellidos }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="mail icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Correo:</strong> {{ user.correo }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="phone icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Teléfono:</strong> {{ user.telefono }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="venus mars icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Género:</strong> {{ user.get_genero_display }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="home icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Dirección:</strong> {{ user.direccion }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui list">
                        <div class="item">
                            <i class="birthday cake icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Fecha de Nacimiento:</strong> {{ profile.fecha_de_nacimiento }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="address card icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Dirección de la Sede:</strong> {{ profile.direccion_sede }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="phone icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Teléfono de la Empresa:</strong> {{ profile.telefono_empresa }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="id card icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Número de Identificación Fiscal:</strong> {{ profile.numero_identificacion_fiscal }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="industry icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Tipo de Empresa:</strong> {{ profile.tipo_empresa }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="industry icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Sector de la Empresa:</strong> {{ profile.sector_empresa }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="users icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Número de Empleados:</strong> {{ profile.numero_empleados }}
                            </div>
                        </div>
                        <div class="item">
                            <i class="info circle icon"></i>
                            <div class="content" style="font-size: 1.2rem;">
                                <strong>Descripción de la Empresa:</strong> {{ profile.descripcion_empresa }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="text-align: center; margin-top: 20px;">
        <a href="{% url 'editar_perfil' %}" class="ui button primary">Editar Perfil</a>
    </div>
    {% else %}
    <div class="ui message">
        <div class="header">Perfil no encontrado</div>
        <p>No se ha creado un perfil para esta cuenta. Haz clic en el botón de abajo para crearlo.</p>
        <a href="{% url 'editar_perfil' %}" class="ui button primary">Crear Perfil</a>
    </div>
    {% endif %}
</div>
{% endblock %}

{% include 'interfaz_admin/pie/footerA.html' %}

workbridgetest1/inicio/templates/accounts/perfil.html
{% load static %}

{% include 'interfaz_admin/pie/headerA.html' %}

{% block content %}
<div class="ui container" style="margin-top: 40px;">
    <div class="ui centered card" style="width: 50%; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); padding: 20px;">
        <div class="ui image" style="text-align: center; margin-bottom: 20px;">
        <center><img src="{% static 'inicio/img/fondo2.jpg' %}" alt="Imagen de perfil del administrador" style="width: 370px;  height: 300px;">
        </center>    
        </div>
        <div class="content">
            <h2 class="ui header" style="text-align: center; margin-top: 0;">Perfil de Administrador</h2>
            <div class="ui divider"></div>
            <div class="description">
                <div class="ui list">
                    <div class="item">
                        <i class="user icon"></i>
                        <div class="content">
                            <strong>Nombre:</strong> {{ user.nombres }} {{ user.apellidos }}
                        </div>
                    </div>
                    <div class="item">
                        <i class="mail icon"></i>
                        <div class="content">
                            <strong>Correo:</strong> {{ user.correo }}
                        </div>
                    </div>
                    <div class="item">
                        <i class="phone icon"></i>
                        <div class="content">
                            <strong>Teléfono:</strong> {{ user.telefono }}
                        </div>
                    </div>
                    <div class="item">
                        <i class="venus mars icon"></i>
                        <div class="content">
                            <strong>Género:</strong> {{ user.get_genero_display }}
                        </div>
                    </div>
                    <div class="item">
                        <i class="home icon"></i>
                        <div class="content">
                            <strong>Dirección:</strong> {{ user.direccion }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% include 'interfaz_admin/pie/footerA.html' %}