workbridgetest1/task1/urls.py
from django.contrib import admin
from django.urls import path, include
from django import views
from . import views
from task1 import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('inicio/', views.inicio, name='inicio'),
    path('creacion/', views.proyectoinsertar, name='creacion'),
    path('indexA/', views.indexA, name='indexA'),
    path('indexE/', views.indexE, name='indexE'),
    path('indexU/', views.indexU, name='indexU'),
    path('inicioE/', views.inicioE, name='inicioE'),
    path('proyectos/actualizar/<int:id>/', views.actualizarproyecto, name='actualizar'),
    path('proyectos/eliminar/<int:id>/', views.borrarproyecto, name='borrar'),
    path('comentariosA/<int:proyecto_id>/', views.comentarios_proyectoA, name='comentariosA'),
    path('comentariosE/<int:proyecto_id>/', views.comentarios_proyectoE, name='comentariosE'),  
    path('comentariosU/<int:proyecto_id>/', views.comentarios_proyectoU, name='comentariosU'),
    path('estadisticas/proyectos/', views.estadisticas_proyectos, name='estadisticas_proyectos'),
    path('estadisticas/', views.estadisticas, name='estadisticas'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workbridgetest1/workbridgetest1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('task1.urls')),
     path('', include('inicio.urls')),
]

workbridgetest1/task1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

"""
class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nom_aprendiz = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    edad = models.IntegerField()
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=20)
    rol = models.CharField(max_length=50)
    
    def __str__(self):
        return f'{self.nom_aprendiz} {self.apellido}'
"""


class Proyecto(models.Model):
    id_proyecto = models.AutoField(primary_key=True)
    nom_proyecto = models.CharField(max_length=255)
    nom_aprendiz = models.CharField(max_length=255)
    descripcion = models.TextField()
    fecha = models.DateField()
    telefono = models.CharField(max_length=15)
    contacto = models.EmailField()
    categoria = models.CharField(max_length=100)
    tiempo_desarrollo = models.PositiveIntegerField(blank=True, null=True)
    tecnologias = models.CharField(max_length=500, blank=True, null=True)
    colaboradores = models.PositiveIntegerField(blank=True, null=True)
    imagen = models.ImageField(upload_to='proyectos/')
    imagen1 = models.ImageField(upload_to='proyectos/', blank=True, null=True)
    imagen2 = models.ImageField(upload_to='proyectos/', blank=True, null=True)
    imagen3 = models.ImageField(upload_to='proyectos/', blank=True, null=True)
    imagen4 = models.ImageField(upload_to='proyectos/', blank=True, null=True)
    
    def __str__(self):
        return self.nom_proyecto



class Comentario(models.Model):
    proyecto = models.ForeignKey(Proyecto, related_name='comentarios', on_delete=models.CASCADE)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    contenido = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    

workbridgetest1/task1/forms.py
from django import forms
from .models import Proyecto, Comentario

class ProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = [
            'nom_proyecto', 'nom_aprendiz', 'descripcion', 'fecha', 'telefono', 'contacto', 
            'categoria', 'tiempo_desarrollo', 'tecnologias', 'colaboradores', 
            'imagen', 'imagen1', 'imagen2', 'imagen3', 'imagen4'
        ]

        
class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']
        widgets = {
            'contenido': forms.Textarea(attrs={'placeholder': 'Escribe tu comentario aquí...', 'rows': 3}),
        }

workbridgetest1/task1/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from task1.models import Proyecto
from .forms import  ProyectoForm, ComentarioForm
from .models import Proyecto,User
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.views.generic import View
from .models import Comentario
from .decorators import admin_required, empresa_required
from django.db.models import Count, Avg, Max, Min



TEMPLACE_DIRS = (
    'os_path.join(BASE_DIR,"templates"),'
)
 

@login_required
def proyectoinsertar(request):
    if request.method == 'POST':
        form = ProyectoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()  
            return redirect('indexA')
    else:
        form = ProyectoForm()
    return render(request, 'interfaz_admin/home/creacion.html', {'form': form})

@login_required
def actualizarproyecto(request, id):
    proyecto = get_object_or_404(Proyecto, id_proyecto=id)
    if request.method == 'POST':
        form = ProyectoForm(request.POST, request.FILES, instance=proyecto)
        if form.is_valid():
            form.save()
            return redirect('indexA')
    else:
        form = ProyectoForm(instance=proyecto)
    return render(request, 'interfaz_admin/home/actualizar.html', {'form': form})

@login_required
def borrarproyecto(request, id):
    proyecto = get_object_or_404(Proyecto, id_proyecto=id)
    if request.method == 'POST':
        proyecto.delete()
        return redirect('indexA')
    return render(request, 'interfaz_admin/home/eliminar.html', {'proyecto': proyecto})

def inicio(request):
    return render(request, 'interfaz_inicio/home/inicio.html')

@login_required
def indexA(request):
    proyectos = Proyecto.objects.all()
    return render(request, 'interfaz_admin/home/indexA.html', {'proyectos': proyectos})

@login_required
def indexE(request):
    proyectos = Proyecto.objects.all()
    return render(request, 'interfaz_empresa/home/indexE.html', {'proyectos': proyectos})

@login_required
def inicioE(request):
    return render(request, 'interfaz_empresa/home/inicioE.html')

def indexU(request):
    proyectos = Proyecto.objects.all()
    return render(request, 'interfaz_inicio/home/indexU.html', {'proyectos': proyectos})


@login_required
@empresa_required
def comentarios_proyectoE(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id_proyecto=proyecto_id)
    comentarios = Comentario.objects.filter(proyecto=proyecto).order_by('-fecha')
    
    if request.method == "POST" and request.user.is_authenticated:
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.proyecto = proyecto
            comentario.usuario = request.user
            comentario.save()
            return redirect('comentariosE', proyecto_id=proyecto.id_proyecto)  # Redireccionar para evitar duplicados
    else:
        form = ComentarioForm()
    
    context = {
        'proyecto': proyecto,
        'comentarios': comentarios,
        'form': form,
    }
    return render(request, 'interfaz_empresa/home/comentariosE.html', context)

@login_required
@empresa_required
def comentarios_proyectoA(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id_proyecto=proyecto_id)
    comentariosA = Comentario.objects.filter(proyecto=proyecto).order_by('-fecha')
    
    if request.method == "POST" and request.user.is_authenticated:
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.proyecto = proyecto
            comentario.usuario = request.user
            comentario.save()
            return redirect('comentariosA', proyecto_id=proyecto.id_proyecto)  # Redireccionar para evitar duplicados
    else:
        form = ComentarioForm()
    
    context = {
        'proyecto': proyecto,
        'comentarios': comentariosA,
        'form': form,
    }
    return render(request, 'interfaz_admin/home/comentariosA.html', context)


def comentarios_proyectoU(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id_proyecto=proyecto_id)
    comentariosU = Comentario.objects.filter(proyecto=proyecto).order_by('-fecha')
    
    context = {
        'proyecto': proyecto,
        'comentarios': comentariosU,
    }
    
    return render(request, 'interfaz_inicio/home/comentariosU.html', context)


"""
def guardar_comentario(request, id_proyecto):
    if request.method == 'POST':
        comentario_texto = request.POST.get('comentario')
        proyecto = get_object_or_404(Proyecto, id_proyecto=id_proyecto)
        comentario_user = User.objects.get(username='Empresa')
        nuevo_comentario = Comentario(proyecto=proyecto, texto=comentario_texto, autor=comentario_user)
        nuevo_comentario.save()
        return redirect('comentarios', id_proyecto=id_proyecto)


"""

"""
class addcomment(View):
    def post(self, request, *args, **kwargs):
        nombre_autor = request.POST.get('nombre_autor')
        texto = request.POST.get('texto')
        proyecto_id = kwargs['proyecto_id']  
        comentario = Comentario(nombre_autor=nombre_autor, texto=texto, proyecto_id=proyecto_id)
        comentario.save()
        return redirect('comentarios', proyecto_id=proyecto_id)

"""



#Estadistica
@login_required
def estadisticas_proyectos(request):
    total_proyectos = Proyecto.objects.count()
    promedio_colaboradores = Proyecto.objects.aggregate(Avg('colaboradores'))['colaboradores__avg']
    max_tiempo_desarrollo = Proyecto.objects.aggregate(Max('tiempo_desarrollo'))['tiempo_desarrollo__max']
    min_tiempo_desarrollo = Proyecto.objects.aggregate(Min('tiempo_desarrollo'))['tiempo_desarrollo__min']
    proyectos_por_categoria = Proyecto.objects.values('categoria').annotate(total=Count('id_proyecto'))

    context = {
        'total_proyectos': total_proyectos,
        'promedio_colaboradores': promedio_colaboradores,
        'max_tiempo_desarrollo': max_tiempo_desarrollo,
        'min_tiempo_desarrollo': min_tiempo_desarrollo,
        'proyectos_por_categoria': list(proyectos_por_categoria),
    }
    return render(request, 'interfaz_admin/estadisticas_proyectos.html', context)



@login_required
def estadisticas(request):
    total_proyectos = Proyecto.objects.count()
    promedio_colaboradores = Proyecto.objects.aggregate(Avg('colaboradores'))['colaboradores__avg']
    max_tiempo_desarrollo = Proyecto.objects.aggregate(Max('tiempo_desarrollo'))['tiempo_desarrollo__max']
    min_tiempo_desarrollo = Proyecto.objects.aggregate(Min('tiempo_desarrollo'))['tiempo_desarrollo__min']
    proyectos_por_categoria = Proyecto.objects.values('categoria').annotate(total=Count('id_proyecto'))

    context = {
        'total_proyectos': total_proyectos,
        'promedio_colaboradores': promedio_colaboradores,
        'max_tiempo_desarrollo': max_tiempo_desarrollo,
        'min_tiempo_desarrollo': min_tiempo_desarrollo,
        'proyectos_por_categoria': list(proyectos_por_categoria),
    }
    return render(request, 'interfaz_empresa/estadisticas.html', context)

workbridgetest1/task1/templates/interfaz_admin/home/actualizar.html
{% load static %}
{% include 'interfaz_admin/pie/headerA.html' %}
<style>
  .ui.container {
    background-color: white; 
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); 
    max-width: 600px; 
    margin: 20px auto; 
  }
  .ui.form .field {
    margin-bottom: 20px; 
  }
  .ui.form label {
    font-weight: bold; 
  }
  .ui.form .image-fields {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
  }
  .ui.form .image-fields .field {
    flex: 1 1 40%; 
  }
  .ui.form .field,
  .ui.form button {
    max-width: 100%; 
  }
</style>


<div class="ui container">
  <h1>Crear Proyecto</h1>
  <form action="" class="ui form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field">
      <label for="id_nom_proyecto">Nombre del Proyecto</label>
      <input type="text" id="id_nom_proyecto" name="nom_proyecto" placeholder="Nombre del Proyecto" value="{{ form.nom_proyecto.value }}" required>
    </div>
    <div class="field">
      <label for="id_nom_aprendiz">Nombre del Aprendiz</label>
      <input type="text" id="id_nom_aprendiz" name="nom_aprendiz" placeholder="Nombre del Aprendiz" value="{{ form.nom_aprendiz.value }}" required>
    </div>
    <div class="field">
      <label for="id_descripcion">Descripción</label>
      <textarea id="id_descripcion" name="descripcion" placeholder="Descripción" required>{{ form.descripcion.value }}</textarea>
    </div>
    <div class="field">
      <label for="id_fecha">Fecha</label>
      <input type="date" id="id_fecha" name="fecha" value="{{ form.fecha.value }}" required>
    </div>
    <div class="field">
      <label for="id_telefono">Teléfono</label>
      <input type="tel" id="id_telefono" name="telefono" placeholder="Teléfono" value="{{ form.telefono.value }}" required>
    </div>
    <div class="field">
      <label for="id_contacto">Correo</label>
      <input type="email" id="id_contacto" name="contacto" placeholder="Correo" value="{{ form.contacto.value }}" required>
    </div>
    <div class="field">
      <label for="id_categoria">Categoría</label>
      <select id="id_categoria" name="categoria" required>
        <option value="">Seleccione una categoría</option>
        <option value="Desarrollo Web" {% if form.categoria.value == "Desarrollo Web" %}selected{% endif %}>Desarrollo Web</option>
        <option value="Aplicación Móviles" {% if form.categoria.value == "Aplicación Móviles" %}selected{% endif %}>Aplicación Móviles</option>
        <option value="Inteligencia Artificial y Machine Learning" {% if form.categoria.value == "Inteligencia Artificial y Machine Learning" %}selected{% endif %}>Inteligencia Artificial y Machine Learning</option>
        <option value="Sistemas de Información y Bases de Datos" {% if form.categoria.value == "Sistemas de Información y Bases de Datos" %}selected{% endif %}>Sistemas de Información y Bases de Datos</option>
      </select>
    </div>
    <div class="field">
      <label for="id_tiempo_desarrollo">Tiempo de Desarrollo (en semanas)</label>
      <input type="number" id="id_tiempo_desarrollo" name="tiempo_desarrollo" placeholder="Tiempo de Desarrollo" value="{{ form.tiempo_desarrollo.value }}" required>
    </div>
    <div class="field">
      <label for="id_tecnologias">Tecnologías Utilizadas</label>
      <input type="text" id="id_tecnologias" name="tecnologias" placeholder="Tecnologías Utilizadas" value="{{ form.tecnologias.value }}" required>
    </div>
    <div class="field">
      <label for="id_colaboradores">Número de Colaboradores</label>
      <input type="number" id="id_colaboradores" name="colaboradores" placeholder="Número de Colaboradores" value="{{ form.colaboradores.value }}" required>
    </div>
    <div class="field">
      <label for="id_imagen">Imagen Principal</label>
      <input type="file" id="id_imagen" name="imagen" accept="image/*">
      {% if form.instance.imagen %}
        <img src="{{ form.instance.imagen.url }}" alt="Imagen actual" style="max-width: 200px; margin-top: 10px;">
      {% endif %}
    </div>
    <div class="field">
      <label for="id_imagen1">Imagen Adicional 1</label>
      <input type="file" id="id_imagen1" name="imagen1" accept="image/*">
      {% if form.instance.imagen1 %}
        <img src="{{ form.instance.imagen1.url }}" alt="Imagen adicional 1 actual" style="max-width: 200px; margin-top: 10px;">
      {% endif %}
    </div>
    <div class="field">
      <label for="id_imagen2">Imagen Adicional 2</label>
      <input type="file" id="id_imagen2" name="imagen2" accept="image/*">
      {% if form.instance.imagen2 %}
        <img src="{{ form.instance.imagen2.url }}" alt="Imagen adicional 2 actual" style="max-width: 200px; margin-top: 10px;">
      {% endif %}
    </div>
    <div class="field">
      <label for="id_imagen3">Imagen Adicional 3</label>
      <input type="file" id="id_imagen3" name="imagen3" accept="image/*">
      {% if form.instance.imagen3 %}
        <img src="{{ form.instance.imagen3.url }}" alt="Imagen adicional 3 actual" style="max-width: 200px; margin-top: 10px;">
      {% endif %}
    </div>
    <div class="field">
      <label for="id_imagen4">Imagen Adicional 4</label>
      <input type="file" id="id_imagen4" name="imagen4" accept="image/*">
      {% if form.instance.imagen4 %}
        <img src="{{ form.instance.imagen4.url }}" alt="Imagen adicional 4 actual" style="max-width: 200px; margin-top: 10px;">
      {% endif %}
    </div>
    <br>
    <button class="ui button primary" type="submit">Enviar</button>
  </form>
</div>

{% include 'interfaz_admin/pie/footerA.html' %}

workbridgetest1/task1/templates/interfaz_admin/home/comentariosA.html
{% load static %}
{% include 'interfaz_admin/pie/headerA.html' %}

<div class="ui container" style="margin-top: 20px;">
    <!-- Información del Proyecto -->
    <div class="ui segment" style="padding: 20px;">
        <div class="image" style="text-align: center; margin-bottom: 20px;">
            <img src="{{ proyecto.imagen.url }}" alt="{{ proyecto.nom_proyecto }}" style="max-width: 100%; height: auto;">
        </div>
        <div class="content">
            <h2 class="ui header">Nombre del Proyecto: {{ proyecto.nom_proyecto }}</h2>
            <div class="meta">
                <span class="date"><strong>Fecha:</strong> {{ proyecto.fecha }}</span>
            </div>
            <div class="description">
                <p><strong>Descripción:</strong> {{ proyecto.descripcion }}</p>
            </div>
            <div class="extra content">
                <p><strong>Teléfono:</strong> {{ proyecto.telefono }}</p>
                <p><strong>Categoría:</strong> {{ proyecto.categoria }}</p>
            </div>
            <div class="extra content">
                <p style="color: gray; font-size: small;"><strong>Proyecto publicado por:</strong> {{ proyecto.nom_aprendiz }}</p>
            </div>
        </div>
    </div>

    <!-- Comentarios -->
    <div class="ui comments" style="margin-top: 20px;">
        <h3 class="ui dividing header">Comentarios</h3>
        {% for comentario in comentarios %}
            <div class="comment">
                <div class="content">
                    <a class="author">{{ comentario.usuario.get_full_name }}</a>
                    <div class="metadata">
                        <span class="date">{{ comentario.fecha }}</span>
                    </div>
                    <div class="text">
                        {{ comentario.contenido }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- Formulario para añadir comentario -->
    <form class="ui reply form" method="POST" action="{% url 'comentariosA' proyecto.id_proyecto %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="ui blue labeled submit icon button" type="submit">
            <i class="icon edit"></i> Añadir Comentario
        </button>
    </form>
</div>

{% include 'interfaz_admin/pie/footerA.html' %}

workbridgetest1/task1/templates/interfaz_admin/home/creacion.html
{% load static %}
{% include 'interfaz_admin/pie/headerA.html' %}

<style>
  .ui.container {
    background-color: white; 
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); 
    max-width: 600px; 
    margin: 20px auto; 
  }
  .ui.form .field {
    margin-bottom: 20px; 
  }
  .ui.form label {
    font-weight: bold; 
  }
  .ui.form .image-fields {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
  }
  .ui.form .image-fields .field {
    flex: 1 1 40%; 
  }
  .ui.form .field,
  .ui.form button {
    max-width: 100%; 
  }
</style>

<div class="ui container">
  <h1>Crear Proyecto</h1>
  <form action="" class="ui form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field">
      <label for="id_nom_proyecto">Nombre del Proyecto</label>
      <input type="text" id="id_nom_proyecto" name="nom_proyecto" placeholder="Nombre del Proyecto" required>
    </div>
    <div class="field">
      <label for="id_nom_aprendiz">Nombre del Aprendiz</label>
      <input type="text" id="id_nom_aprendiz" name="nom_aprendiz" placeholder="Nombre del Aprendiz" required>
    </div>
    <div class="field">
      <label for="id_descripcion">Descripción</label>
      <textarea id="id_descripcion" name="descripcion" placeholder="Descripción" required></textarea>
    </div>
    <div class="field">
      <label for="id_fecha">Fecha</label>
      <input type="date" id="id_fecha" name="fecha" required>
    </div>
    <div class="field">
      <label for="id_telefono">Teléfono</label>
      <input type="tel" id="id_telefono" name="telefono" placeholder="Teléfono" required>
    </div>
    <div class="field">
      <label for="id_contacto">Correo</label>
      <input type="email" id="id_contacto" name="contacto" placeholder="Correo" required>
    </div>
    <div class="field">
      <label for="id_categoria">Categoría</label>
      <select id="id_categoria" name="categoria" required>
        <option value="">Seleccione una categoría</option>
        <option value="Desarrollo Web">Desarrollo Web</option>
        <option value="Aplicación Móviles">Aplicación Móviles</option>
        <option value="Inteligencia Artificial y Machine Learning">Inteligencia Artificial y Machine Learning</option>
        <option value="Sistemas de Información y Bases de Datos">Sistemas de Información y Bases de Datos</option>
      </select>
    </div>
    <div class="field">
      <label for="id_tiempo_desarrollo">Tiempo de Desarrollo (en semanas)</label>
      <input type="number" id="id_tiempo_desarrollo" name="tiempo_desarrollo" placeholder="Tiempo de Desarrollo" required>
    </div>
    <div class="field">
      <label for="id_tecnologias">Tecnologías Utilizadas</label>
      <input type="text" id="id_tecnologias" name="tecnologias" placeholder="Tecnologías Utilizadas" required>
    </div>
    <div class="field">
      <label for="id_colaboradores">Número de Colaboradores</label>
      <input type="number" id="id_colaboradores" name="colaboradores" placeholder="Número de Colaboradores" required>
    </div>
    <div class="field">
      <label>Imágenes</label>
      <div class="image-fields">
        <div class="field">
          <label for="id_imagen">Imagen Principal</label>
          <input type="file" id="id_imagen" name="imagen" accept="image/*" required>
        </div>
        <div class="field">
          <label for="id_imagen1">Imagen Adicional 1</label>
          <input type="file" id="id_imagen1" name="imagen1" accept="image/*">
        </div>
        <div class="field">
          <label for="id_imagen2">Imagen Adicional 2</label>
          <input type="file" id="id_imagen2" name="imagen2" accept="image/*">
        </div>
        <div class="field">
          <label for="id_imagen3">Imagen Adicional 3</label>
          <input type="file" id="id_imagen3" name="imagen3" accept="image/*">
        </div>
        <div class="field">
          <label for="id_imagen4">Imagen Adicional 4</label>
          <input type="file" id="id_imagen4" name="imagen4" accept="image/*">
        </div>
      </div>
    </div>
    <br>
    <div style="text-align: center;">
      <button class="ui button primary" type="submit">Enviar</button>
    </div>
  </form>
</div>

{% include 'interfaz_admin/pie/footerA.html' %}

workbridgetest1/task1/templates/interfaz_admin/home/eliminar.html
{% load static %}
{% include 'interfaz_admin/pie/headerA.html' %}

<div class="ui container" style="margin-top: 40px; padding: 40px; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2); border-radius: 10px; background-color: #f9f9f9;">
    <h1 class="ui header" style="font-family: 'Lato', sans-serif; color: #db2828;">Eliminar Proyecto</h1>
    <p style="font-size: 1.2em; color: #333;">¿Estás seguro de que deseas eliminar el proyecto <strong>"{{ proyecto.nom_proyecto }}"</strong>?</p>
    <form action="" method="POST" style="margin-top: 20px;">
        {% csrf_token %}
        <button class="ui red button" type="submit" style="margin-right: 10px;"><i class="trash icon"></i> Eliminar</button>
        <a href="{% url 'indexA' %}" class="ui button"><i class="cancel icon"></i> Cancelar</a>
    </form>
</div>

{% include 'interfaz_admin/pie/footerA.html' %}

<style>
    .ui.container {
        font-family: 'Lato', sans-serif;
    }
    .ui.header {
        font-size: 2.5em;
    }
    .ui.container p {
        font-size: 1.2em;
        color: #333;
    }
    .ui.button.red {
        background-color: #ad3030;
        color: #fff;
    }
    .ui.button.red:hover {
        background-color: #a82222;
    }
    .ui.button {
        background-color: #f9f9f9;
        color: #333;
        border: 1px solid #ccc;
    }
    .ui.button:hover {
        background-color: #e0e0e0;
    }
    </style>
    

workbridgetest1/task1/templates/interfaz_admin/home/indexA.html
{% load static %}
{% include 'interfaz_admin/pie/headerA.html' %}

<div class="ui container" style="margin-top: 20px;">
    <div class="ui stackable grid">
        {% for proyecto in proyectos %}
            <div class="four wide column">
                <div class="ui card" style="height: 500px;">
                    <div class="image" style="height: 200px; overflow: hidden;">
                        <img src="{{ proyecto.imagen.url }}" alt="{{ proyecto.nom_proyecto }}" style="object-fit: cover; height: 100%; width: 100%;">
                    </div>
                    <div class="content" style="height: 200px; overflow: hidden;">
                        <a class="header">{{ proyecto.nom_proyecto }}</a>
                        <div class="meta">
                            <span class="date">Fecha: {{ proyecto.fecha }}</span>
                        </div>
                        <div class="description">
                            {% if proyecto.descripcion|length > 150 %}
                                {{ proyecto.descripcion|slice:":147" }}...
                            {% else %}
                                {{ proyecto.descripcion }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="extra content" style="height: 100px; overflow: hidden;">
                        <span>Teléfono: {{ proyecto.telefono }}</span>
                        <br>
                        <span>Categoría: {{ proyecto.categoria }}</span>
                        <br>
                        <p style="color: gray; font-size: small;">Proyecto publicado por: {{ proyecto.nom_aprendiz }}</p>
                    </div>
                    <div class="extra content">
                        <a href="{% url 'actualizar' proyecto.id_proyecto %}"><i class="edit icon"></i></a>
                        <a href="{% url 'borrar' proyecto.id_proyecto %}"><i class="trash icon"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% include 'interfaz_admin/pie/footerA.html' %}